//For sections required in every page; like Navbars or footers
import { Jost } from "next/font/google";
import "./globals.css";

//Components
import Navbar from "./components/Navbar";

const jost = Jost({ subsets: ["latin"] });    //Instance of font

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    //'nav' tag under body, before '{children}'
    <html lang="en">
      <body className={jost.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
